default['protocol-hub-api']['db']['host'] = 'localhost:5432'
default['protocol-hub-api']['secrets_file'] = 'hub.sana-test'
default['protocol-hub-api']['repository'] = 'https://github.com/delta-crew/sana.protocol_hub.api'
default['protocol-hub-api']['revision'] = 'master'
default['protocol-hub-api']['bind_address'] = '127.0.0.1:8000'
